### ISSUE TITLE
изменения в распиновке

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-112-17#12]
https://github.com/rusefi/rusefi/commit/9bc75bf3ef2a4f8ac3f90c525db7b07e5ac62391 - там же пометки пинов, где точно нужны джамперы

**Comment by Qwerty-OFF** [comment]
Все джамперы по умолчанию установлены?

**Comment by rusefillc** [comment]
> Все джамперы по умолчанию установлены?

да
