### ISSUE TITLE
digital inputs note

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-112-17#13]
мы сейчас такие поддерживаем? или у нас обычно подтяжки?

![image](https://github.com/rusefi/hellen-112-17/assets/48498823/482637e4-4456-47de-a93e-227df6774bc9)

**Comment by Qwerty-OFF** [comment]
Подтяжки к земле поддерживаем

**Comment by Qwerty-OFF** [comment]
Подтяжки к земле по умолчанию. Если что, можно переставить резистор для подтяжки вверх.
![image](https://github.com/rusefi/hellen-112-17/assets/4116383/270d424c-55e2-4075-9888-11784cc07d3c)
