### ISSUE TITLE
rev A test log was обжёгся в районе кнопки PROG

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-112-17#21]
получил две собранные платы
нажал PROG
подключил mini-UBS
обжёгся где-то в районе нажал PROG

один синий светодиод на блоке питания горит постоянно, второй медленно мигает
DFU устройство в Windows не появилось

**Comment by rusefillc** [comment]
with pin lifted I was able to DFU program

![image](https://github.com/rusefi/hellen-112-17/assets/48498823/e7a20373-d839-4179-8fc5-db5846e89e69)

**Comment by Qwerty-OFF** [comment]
Починено в ММ100_0.2
